#Requires -Version 5.1
<#
.SYNOPSIS
    WSTT — Windows Server Troubleshooting Tool root module.
.DESCRIPTION
    Dot-sources every file in Source/ in lexical order so that $script:-scoped
    variables (Constants, Findings store, OS capability cache) are shared across
    all helpers. Source files are auto-generated by tools\Split-Module.ps1 from
    the original WSTT_v4.0.ps1 monolith.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$sourceFiles = Get-ChildItem -Path (Join-Path $PSScriptRoot 'Source') -Filter '*.ps1' |
               Sort-Object Name

foreach ($file in $sourceFiles) {
    try {
        . $file.FullName
    } catch {
        Write-Error "Failed to load WSTT source '$($file.Name)': $_"
        throw
    }
}

# Export every public-facing function. Internal helpers are filtered by name
# convention (Write-Diag*, Get-Validated*, Initialize-*, etc.) — but for v4.0
# we keep the surface broad so existing callers and tests continue to work.
Export-ModuleMember -Function * -Cmdlet * -Alias *
